// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uidvkljqszoswzatkpqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZHZrbGpxc3pvc3d6YXRrcHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzUwOTUsImV4cCI6MjA3MzYxMTA5NX0.PXa6zyNgdDbGFZ07EZSEG74huk8CWUQE9UiqDlmNWuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});